// AUTO-GENERATED by tools/gen_hachimi_settings.py -- DO NOT EDIT BY HAND.
// Regenerate after changing EqualizerSettings / PlaybackOutputSettings.
package com.tencent.ibg.joox.data.settings

import com.qing.hachimi.audio.EqualizerSettings
import com.qing.hachimi.audio.HACHIMI_BIT_DEPTH_AUTO
import com.qing.hachimi.dsp.TenBandEqualizer
import com.qing.hachimi.audio.PlaybackOutputSettings
import org.json.JSONArray
import org.json.JSONObject

/**
 * Persistable mirror of the Hachimi audio engine settings.
 *
 * Field names are prefixed (`eq` -> the DSP class, `ob` -> the output class) so the snapshot
 * stays unambiguous. Defaults mirror the upstream DSP defaults exactly; unknown or missing
 * JSON keys always fall back to those defaults so a payload written by an older build keeps
 * loading.
 */
data class HachimiSoundSnapshot(
    val eqEnabled: Boolean = false,
    val eqBandGainsDb: FloatArray = FloatArray(TenBandEqualizer.BAND_COUNT) { 0f },
    val eqMasterGainDb: Float = 0f,
    val eqEqQ: Float = EqualizerSettings.EQ_DEFAULT_Q,
    val eqBassGainDb: Float = 0f,
    val eqTrebleGainDb: Float = 0f,
    val eqCompressorEnabled: Boolean = false,
    val eqCompressorThresholdDb: Float = -18f,
    val eqCompressorRatio: Float = 2f,
    val eqCompressorMakeupDb: Float = 0f,
    val eqStereoWidth: Float = 1f,
    val eqReverbPreset: Int = 0,
    val eqSurround360Enabled: Boolean = false,
    val eqSurround360Intensity: Float = 50f,
    val eqSurround360RotationSpeed: Float = 30f,
    val eqPanoramic360Enabled: Boolean = false,
    val eqPanoramic360Intensity: Float = 50f,
    val eqPanoramic360AzimuthDegrees: Float = 0f,
    val eqPanoramic360ElevationDegrees: Float = 0f,
    val eqLoudnessBalanceEnabled: Boolean = false,
    val eqLoudnessPercent: Float = 35f,
    val eqChannelBalance: Float = 0f,
    val eqCrossfeedEnabled: Boolean = false,
    val eqCrossfeedLowCutHz: Float = 300f,
    val eqCrossfeedHighCutHz: Float = 2_000f,
    val eqCrossfeedAttenuationDb: Float = 6f,
    val eqMonoBassEnabled: Boolean = false,
    val eqMonoBassCrossoverHz: Float = 120f,
    val eqMonoBassAmount: Float = 100f,
    val eqSpeakerOutputEnabled: Boolean = false,
    val eqSpeakerOutputMode: Int = 0,
    val eqSpeakerOutputStrength: Float = 82f,
    val eqDynamicEqEnabled: Boolean = false,
    val eqDynamicEqIntensity: Float = 50f,
    val eqDeEsserAmount: Float = 45f,
    val eqDeEsserFrequencyHz: Float = 6_500f,
    val eqMoogLadderEnabled: Boolean = false,
    val eqMoogLadderMode: Int = 0,
    val eqMoogLadderCutoffHz: Float = 12_000f,
    val eqMoogLadderResonance: Float = 20f,
    val eqMoogLadderDriveDb: Float = 0f,
    val eqMoogLadderMix: Float = 100f,
    val eqPeakLimiterEnabled: Boolean = true,
    val obBitDepth: String = HACHIMI_BIT_DEPTH_AUTO,
    val obSampleRate: Int = 0,
    val obBackend: String = "auto",
    val obUsbExclusive: Boolean = false,
    val obUsbPinned: Boolean = false
) {

    fun toEqualizerSettings(): EqualizerSettings = EqualizerSettings(
        enabled = eqEnabled,
        bandGainsDb = eqBandGainsDb,
        masterGainDb = eqMasterGainDb,
        eqQ = eqEqQ,
        bassGainDb = eqBassGainDb,
        trebleGainDb = eqTrebleGainDb,
        compressorEnabled = eqCompressorEnabled,
        compressorThresholdDb = eqCompressorThresholdDb,
        compressorRatio = eqCompressorRatio,
        compressorMakeupDb = eqCompressorMakeupDb,
        stereoWidth = eqStereoWidth,
        reverbPreset = eqReverbPreset,
        surround360Enabled = eqSurround360Enabled,
        surround360Intensity = eqSurround360Intensity,
        surround360RotationSpeed = eqSurround360RotationSpeed,
        panoramic360Enabled = eqPanoramic360Enabled,
        panoramic360Intensity = eqPanoramic360Intensity,
        panoramic360AzimuthDegrees = eqPanoramic360AzimuthDegrees,
        panoramic360ElevationDegrees = eqPanoramic360ElevationDegrees,
        loudnessBalanceEnabled = eqLoudnessBalanceEnabled,
        loudnessPercent = eqLoudnessPercent,
        channelBalance = eqChannelBalance,
        crossfeedEnabled = eqCrossfeedEnabled,
        crossfeedLowCutHz = eqCrossfeedLowCutHz,
        crossfeedHighCutHz = eqCrossfeedHighCutHz,
        crossfeedAttenuationDb = eqCrossfeedAttenuationDb,
        monoBassEnabled = eqMonoBassEnabled,
        monoBassCrossoverHz = eqMonoBassCrossoverHz,
        monoBassAmount = eqMonoBassAmount,
        speakerOutputEnabled = eqSpeakerOutputEnabled,
        speakerOutputMode = eqSpeakerOutputMode,
        speakerOutputStrength = eqSpeakerOutputStrength,
        dynamicEqEnabled = eqDynamicEqEnabled,
        dynamicEqIntensity = eqDynamicEqIntensity,
        deEsserAmount = eqDeEsserAmount,
        deEsserFrequencyHz = eqDeEsserFrequencyHz,
        moogLadderEnabled = eqMoogLadderEnabled,
        moogLadderMode = eqMoogLadderMode,
        moogLadderCutoffHz = eqMoogLadderCutoffHz,
        moogLadderResonance = eqMoogLadderResonance,
        moogLadderDriveDb = eqMoogLadderDriveDb,
        moogLadderMix = eqMoogLadderMix,
        peakLimiterEnabled = eqPeakLimiterEnabled
    )

    fun toOutputSettings(): PlaybackOutputSettings = PlaybackOutputSettings(
        bitDepth = obBitDepth,
        sampleRate = obSampleRate,
        backend = obBackend,
        usbExclusive = obUsbExclusive,
        usbPinned = obUsbPinned
    )

    fun toJson(): JSONObject = JSONObject().apply {
        put("eqEnabled", eqEnabled)
        put("eqBandGainsDb", JSONArray(eqBandGainsDb.map { it.toDouble() }))
        put("eqMasterGainDb", eqMasterGainDb)
        put("eqEqQ", eqEqQ)
        put("eqBassGainDb", eqBassGainDb)
        put("eqTrebleGainDb", eqTrebleGainDb)
        put("eqCompressorEnabled", eqCompressorEnabled)
        put("eqCompressorThresholdDb", eqCompressorThresholdDb)
        put("eqCompressorRatio", eqCompressorRatio)
        put("eqCompressorMakeupDb", eqCompressorMakeupDb)
        put("eqStereoWidth", eqStereoWidth)
        put("eqReverbPreset", eqReverbPreset)
        put("eqSurround360Enabled", eqSurround360Enabled)
        put("eqSurround360Intensity", eqSurround360Intensity)
        put("eqSurround360RotationSpeed", eqSurround360RotationSpeed)
        put("eqPanoramic360Enabled", eqPanoramic360Enabled)
        put("eqPanoramic360Intensity", eqPanoramic360Intensity)
        put("eqPanoramic360AzimuthDegrees", eqPanoramic360AzimuthDegrees)
        put("eqPanoramic360ElevationDegrees", eqPanoramic360ElevationDegrees)
        put("eqLoudnessBalanceEnabled", eqLoudnessBalanceEnabled)
        put("eqLoudnessPercent", eqLoudnessPercent)
        put("eqChannelBalance", eqChannelBalance)
        put("eqCrossfeedEnabled", eqCrossfeedEnabled)
        put("eqCrossfeedLowCutHz", eqCrossfeedLowCutHz)
        put("eqCrossfeedHighCutHz", eqCrossfeedHighCutHz)
        put("eqCrossfeedAttenuationDb", eqCrossfeedAttenuationDb)
        put("eqMonoBassEnabled", eqMonoBassEnabled)
        put("eqMonoBassCrossoverHz", eqMonoBassCrossoverHz)
        put("eqMonoBassAmount", eqMonoBassAmount)
        put("eqSpeakerOutputEnabled", eqSpeakerOutputEnabled)
        put("eqSpeakerOutputMode", eqSpeakerOutputMode)
        put("eqSpeakerOutputStrength", eqSpeakerOutputStrength)
        put("eqDynamicEqEnabled", eqDynamicEqEnabled)
        put("eqDynamicEqIntensity", eqDynamicEqIntensity)
        put("eqDeEsserAmount", eqDeEsserAmount)
        put("eqDeEsserFrequencyHz", eqDeEsserFrequencyHz)
        put("eqMoogLadderEnabled", eqMoogLadderEnabled)
        put("eqMoogLadderMode", eqMoogLadderMode)
        put("eqMoogLadderCutoffHz", eqMoogLadderCutoffHz)
        put("eqMoogLadderResonance", eqMoogLadderResonance)
        put("eqMoogLadderDriveDb", eqMoogLadderDriveDb)
        put("eqMoogLadderMix", eqMoogLadderMix)
        put("eqPeakLimiterEnabled", eqPeakLimiterEnabled)
        put("obBitDepth", obBitDepth)
        put("obSampleRate", obSampleRate)
        put("obBackend", obBackend)
        put("obUsbExclusive", obUsbExclusive)
        put("obUsbPinned", obUsbPinned)
    }

    companion object {
        val DEFAULT = HachimiSoundSnapshot()

        fun fromJson(obj: JSONObject?): HachimiSoundSnapshot {
            if (obj == null) return DEFAULT
            return HachimiSoundSnapshot(
                eqEnabled = obj.optBooleanOrNull("eqEnabled") ?: DEFAULT.eqEnabled,
                eqBandGainsDb = obj.optFloatArrayOrNull("eqBandGainsDb") ?: DEFAULT.eqBandGainsDb,
                eqMasterGainDb = obj.optFloatOrNull("eqMasterGainDb") ?: DEFAULT.eqMasterGainDb,
                eqEqQ = obj.optFloatOrNull("eqEqQ") ?: DEFAULT.eqEqQ,
                eqBassGainDb = obj.optFloatOrNull("eqBassGainDb") ?: DEFAULT.eqBassGainDb,
                eqTrebleGainDb = obj.optFloatOrNull("eqTrebleGainDb") ?: DEFAULT.eqTrebleGainDb,
                eqCompressorEnabled = obj.optBooleanOrNull("eqCompressorEnabled") ?: DEFAULT.eqCompressorEnabled,
                eqCompressorThresholdDb = obj.optFloatOrNull("eqCompressorThresholdDb") ?: DEFAULT.eqCompressorThresholdDb,
                eqCompressorRatio = obj.optFloatOrNull("eqCompressorRatio") ?: DEFAULT.eqCompressorRatio,
                eqCompressorMakeupDb = obj.optFloatOrNull("eqCompressorMakeupDb") ?: DEFAULT.eqCompressorMakeupDb,
                eqStereoWidth = obj.optFloatOrNull("eqStereoWidth") ?: DEFAULT.eqStereoWidth,
                eqReverbPreset = obj.optIntOrNull("eqReverbPreset") ?: DEFAULT.eqReverbPreset,
                eqSurround360Enabled = obj.optBooleanOrNull("eqSurround360Enabled") ?: DEFAULT.eqSurround360Enabled,
                eqSurround360Intensity = obj.optFloatOrNull("eqSurround360Intensity") ?: DEFAULT.eqSurround360Intensity,
                eqSurround360RotationSpeed = obj.optFloatOrNull("eqSurround360RotationSpeed") ?: DEFAULT.eqSurround360RotationSpeed,
                eqPanoramic360Enabled = obj.optBooleanOrNull("eqPanoramic360Enabled") ?: DEFAULT.eqPanoramic360Enabled,
                eqPanoramic360Intensity = obj.optFloatOrNull("eqPanoramic360Intensity") ?: DEFAULT.eqPanoramic360Intensity,
                eqPanoramic360AzimuthDegrees = obj.optFloatOrNull("eqPanoramic360AzimuthDegrees") ?: DEFAULT.eqPanoramic360AzimuthDegrees,
                eqPanoramic360ElevationDegrees = obj.optFloatOrNull("eqPanoramic360ElevationDegrees") ?: DEFAULT.eqPanoramic360ElevationDegrees,
                eqLoudnessBalanceEnabled = obj.optBooleanOrNull("eqLoudnessBalanceEnabled") ?: DEFAULT.eqLoudnessBalanceEnabled,
                eqLoudnessPercent = obj.optFloatOrNull("eqLoudnessPercent") ?: DEFAULT.eqLoudnessPercent,
                eqChannelBalance = obj.optFloatOrNull("eqChannelBalance") ?: DEFAULT.eqChannelBalance,
                eqCrossfeedEnabled = obj.optBooleanOrNull("eqCrossfeedEnabled") ?: DEFAULT.eqCrossfeedEnabled,
                eqCrossfeedLowCutHz = obj.optFloatOrNull("eqCrossfeedLowCutHz") ?: DEFAULT.eqCrossfeedLowCutHz,
                eqCrossfeedHighCutHz = obj.optFloatOrNull("eqCrossfeedHighCutHz") ?: DEFAULT.eqCrossfeedHighCutHz,
                eqCrossfeedAttenuationDb = obj.optFloatOrNull("eqCrossfeedAttenuationDb") ?: DEFAULT.eqCrossfeedAttenuationDb,
                eqMonoBassEnabled = obj.optBooleanOrNull("eqMonoBassEnabled") ?: DEFAULT.eqMonoBassEnabled,
                eqMonoBassCrossoverHz = obj.optFloatOrNull("eqMonoBassCrossoverHz") ?: DEFAULT.eqMonoBassCrossoverHz,
                eqMonoBassAmount = obj.optFloatOrNull("eqMonoBassAmount") ?: DEFAULT.eqMonoBassAmount,
                eqSpeakerOutputEnabled = obj.optBooleanOrNull("eqSpeakerOutputEnabled") ?: DEFAULT.eqSpeakerOutputEnabled,
                eqSpeakerOutputMode = obj.optIntOrNull("eqSpeakerOutputMode") ?: DEFAULT.eqSpeakerOutputMode,
                eqSpeakerOutputStrength = obj.optFloatOrNull("eqSpeakerOutputStrength") ?: DEFAULT.eqSpeakerOutputStrength,
                eqDynamicEqEnabled = obj.optBooleanOrNull("eqDynamicEqEnabled") ?: DEFAULT.eqDynamicEqEnabled,
                eqDynamicEqIntensity = obj.optFloatOrNull("eqDynamicEqIntensity") ?: DEFAULT.eqDynamicEqIntensity,
                eqDeEsserAmount = obj.optFloatOrNull("eqDeEsserAmount") ?: DEFAULT.eqDeEsserAmount,
                eqDeEsserFrequencyHz = obj.optFloatOrNull("eqDeEsserFrequencyHz") ?: DEFAULT.eqDeEsserFrequencyHz,
                eqMoogLadderEnabled = obj.optBooleanOrNull("eqMoogLadderEnabled") ?: DEFAULT.eqMoogLadderEnabled,
                eqMoogLadderMode = obj.optIntOrNull("eqMoogLadderMode") ?: DEFAULT.eqMoogLadderMode,
                eqMoogLadderCutoffHz = obj.optFloatOrNull("eqMoogLadderCutoffHz") ?: DEFAULT.eqMoogLadderCutoffHz,
                eqMoogLadderResonance = obj.optFloatOrNull("eqMoogLadderResonance") ?: DEFAULT.eqMoogLadderResonance,
                eqMoogLadderDriveDb = obj.optFloatOrNull("eqMoogLadderDriveDb") ?: DEFAULT.eqMoogLadderDriveDb,
                eqMoogLadderMix = obj.optFloatOrNull("eqMoogLadderMix") ?: DEFAULT.eqMoogLadderMix,
                eqPeakLimiterEnabled = obj.optBooleanOrNull("eqPeakLimiterEnabled") ?: DEFAULT.eqPeakLimiterEnabled,
                obBitDepth = obj.optStringOrNull("obBitDepth") ?: DEFAULT.obBitDepth,
                obSampleRate = obj.optIntOrNull("obSampleRate") ?: DEFAULT.obSampleRate,
                obBackend = obj.optStringOrNull("obBackend") ?: DEFAULT.obBackend,
                obUsbExclusive = obj.optBooleanOrNull("obUsbExclusive") ?: DEFAULT.obUsbExclusive,
                obUsbPinned = obj.optBooleanOrNull("obUsbPinned") ?: DEFAULT.obUsbPinned
            )
        }

        fun fromJsonString(raw: String?): HachimiSoundSnapshot {
            if (raw.isNullOrBlank()) return DEFAULT
            return runCatching { fromJson(JSONObject(raw)) }.getOrDefault(DEFAULT)
        }
    }
}

private inline fun JSONObject.optFloatOrNull(key: String): Float? =
    if (has(key)) optDouble(key).toFloat() else null

private inline fun JSONObject.optIntOrNull(key: String): Int? =
    if (has(key)) optInt(key) else null

private inline fun JSONObject.optLongOrNull(key: String): Long? =
    if (has(key)) optLong(key) else null

private inline fun JSONObject.optBooleanOrNull(key: String): Boolean? =
    if (has(key)) optBoolean(key) else null

private inline fun JSONObject.optStringOrNull(key: String): String? =
    if (has(key)) optString(key).takeIf { it.isNotEmpty() } else null

private fun JSONObject.optFloatArrayOrNull(key: String): FloatArray? {
    if (!has(key)) return null
    val arr = optJSONArray(key) ?: return null
    return FloatArray(arr.length()) { i -> arr.optDouble(i, 0.0).toFloat() }
}

private fun JSONArray.toFloatArray(): FloatArray =
    FloatArray(length()) { i -> optDouble(i, 0.0).toFloat() }
